version: '3.8'

services:
  # PostgreSQL Database for Job Scheduler
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: agrisense_jobs
      POSTGRES_USER: agrisense
      POSTGRES_PASSWORD: agrisense_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agrisense"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for Message Queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Django Job Scheduler Service
  job_scheduler:
    build:
      context: ./job_scheduler
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://agrisense:agrisense_password@postgres:5432/agrisense_jobs
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./job_scheduler:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # Celery Worker for Job Processing
  celery_worker:
    build:
      context: ./job_scheduler
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://agrisense:agrisense_password@postgres:5432/agrisense_jobs
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./job_scheduler:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A job_scheduler worker --loglevel=info

  # Celery Beat for Scheduled Jobs
  celery_beat:
    build:
      context: ./job_scheduler
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://agrisense:agrisense_password@postgres:5432/agrisense_jobs
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./job_scheduler:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A job_scheduler beat --loglevel=info

  # Data Pipeline Worker
  data_pipeline_worker:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    command: python worker.py

volumes:
  postgres_data:
  redis_data:
